#!/bin/bash

set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $SERVICE_DB_USER WITH ENCRYPTED PASSWORD '$SERVICE_DB_PASS';
  ALTER USER $SERVICE_DB_USER CREATEDB;
  CREATE DATABASE $SERVICE_DB_NAME;
  GRANT ALL PRIVILEGES ON DATABASE $SERVICE_DB_NAME TO $SERVICE_DB_USER;
EOSQL